---
abstract: 'Gantt charts for your tickets'
author:
  - 'sunnavy <sunnavy@bestpractical.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: gplv2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-JSGantt
no_index:
  directory:
    - etc
    - html
    - inc
requires:
  JSON: 0
resources:
  repository: git://github.com/bestpractical/rt-extension-jsgantt.git
version: 0.11
